<?xml version="1.0" encoding="UTF-8"?>

<!--引入dtd约束xml-->
<!DOCTYPE stus SYSTEM "stus.dtd">
<!--引入本地dtd 根标签名字 SYSTEM "dtd位置"-->

<!--xml文档直接内嵌方式-->
<!--<!DOCTYPE stus[-->
        <!--<!ELEMENT stus (stu)>-->
        <!--<!ELEMENT stu (name,age)>-->
        <!--<!ELEMENT name (#PCDATA)>-->
        <!--<!ELEMENT age (#PCDATA)>-->
        <!--]>-->
<stus>
    <stu id="10086" >
        <name>张三</name>
        <age>18</age>
    </stu>
    <stu id="10087">
        <name>李四</name>
        <age>29</age>
    </stu>
</stus>